### ISSUE TITLE
Basic Layout of Canvas, Tools and Properties

### ISSUE THREAD

**Issue by Abdallah-Moh** [PhotostatEditor/Photostat#11]
Before we start working on any thing we will need to have the simple paned with a grid called canvas. we will replace the canvas grid with what `cairo` library needs and the left and right grid will be empty

**Comment by colinkiama** [comment]
What is a "paned"? Did you mean "panel"?

**Comment by Abdallah-Moh** [comment]
@colinkiama  No. the Gtk.Paned basicly the resizable panels
- Layers Panel
- Properties panel

**Comment by colinkiama** [comment]
I think that @Suzie97 should make a mockup of what this would look like first or you could link some examples of how you would like it to look like/

**Comment by Abdallah-Moh** [comment]
We have one
