### ISSUE TITLE
Add options to hide headerbar icon labels, use symbolic icons

### ISSUE THREAD

**Issue by Abdallah-Moh** [PhotostatEditor/Photostat#14]
### Add options to hide headerbar icon labels, use symbolic icons

**Comment by Suzie97** [comment]
I'm thinking of not providing any labels for the headerbar buttons. By default, we want to keep it clean and the icons are pretty self explanatory. Share your thoughts

**Comment by Abdallah-Moh** [comment]
Some users may want it just provide an option to hide them

**Comment by Suzie97** [comment]
How about providing an option to show them? By default keeping them hidden, because on hover the buttons will display a tooltip anyways.

**Comment by Abdallah-Moh** [comment]
yes
