### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by Suzie97** [PhotostatEditor/Photostat#16]
I created a branch called `translation-support`. 

I can't resolve an error while trying to add translations. @syfds @Abdallah-Moh, you might want to check out that branch.

**Comment by Abdallah-Moh** [comment]
@Suzie97 I heard of something called weblate I think it is used for managing translation and its progress and any one can translate from there

**Comment by Abdallah-Moh** [comment]
I wan to translate my language `Arabic` what should be the file name

**Comment by Suzie97** [comment]
No, the branch is not ready to allow for translations. 

`ninja com.github.yourusername.yourrepositoryname-pot`
This command for generating the `.pot`file fails

**Comment by Abdallah-Moh** [comment]
I will try to fix it

**Comment by syfds** [comment]
hi @Suzie97 , I created a PR based on master, the translation-support branch is little bit outdated.
