### ISSUE TITLE
Create flatpak manifest

### ISSUE THREAD

**Issue by Suzie97** [PhotostatEditor/Photostat#18]
This is necessary as per the new packaging method for elementary OS.

Also, it will let users test the app without having to install all the dependencies. And it is a good idea to handle this early on, so that we can see what will work in a flatpak sandbox rather than implementing a bunch of changes and then realizing that it doesn't work as a flatpak sandbox.

**Comment by Suzie97** [comment]
Useful links: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging
                    https://docs.flatpak.org/en/latest/introduction.html

**Comment by Abdallah-Moh** [comment]
I will work on it
