### ISSUE TITLE
README file should specify that elementary SDK is required to be installed for testing with Flatpak

### ISSUE THREAD

**Issue by colinkiama** [PhotostatEditor/Photostat#31]
While the Flatpak installer will mention that the elementary SDK package is required, the link to the elementary dev documentation: https://docs.elementary.io/develop/writing-apps/the-basic-setup#flatpak or just writing those instructions here will make things more straightforward for other people curious about the project.

**Comment by Abdallah-Moh** [comment]
### `Done`
