### ISSUE TITLE
Flatpak should be the main way of testing 

### ISSUE THREAD

**Issue by hanaral** [PhotostatEditor/Photostat#41]
## Problem

Currently the readme puts root installs as the main build method, flatpak being below it

## Proposal

Like many other elementary and appcenter apps, the main method of building,testing and uninstalling should be via flatpak. Not only does this make testing specific to the format that the app will be shipped and sold as, but it makes testing itself easier and more accessible:
- 0 dependencies besides flatpak and flatpak-builder
- The app is isolated when installed via build and won't bring in any unnecessary "extras" you have to uninstall when removing the testing app
- The app can be uninstalled completely with 1 or 2 commands

I would even recommend removing any mention of root installs or saying that it's completely unsupported (at your own risk)

## Prior Art

<any other elementary app>

**Comment by ghost** [comment]
Done.
